#!/usr/bin/env bash
# Generate <book>/chapter_versions.tex from git history.
# Usage: tools/update_chapter_versions.sh <book_dir>
#
# For each chapters/*.tex file, the script extracts the most recent commit's
# short hash and date that touched that file, derives a deterministic
# adjective/fruit/Tier triple from the hash, and writes one
# \setchapterversion{key}{date}{name} line per chapter into
# <book_dir>/chapter_versions.tex. The full book and each per-chapter
# wrapper input that file in their preamble.
set -euo pipefail

if [[ $# -ne 1 ]]; then
  echo "Usage: $0 <book_dir>" >&2
  exit 2
fi

BOOK_DIR="$(cd "$1" && pwd)"
SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
WORDS_DIR="$SCRIPT_DIR/words"
OUT="$BOOK_DIR/chapter_versions.tex"
REPO_ROOT="$(git rev-parse --show-toplevel)"

if [[ ! -d "$BOOK_DIR/chapters" ]]; then
  echo "No chapters/ directory in $BOOK_DIR" >&2
  exit 1
fi

# Pick a working Python >= 3.9 (version_word.py uses PEP 585 generics).
# On macOS/Linux this is normally python3. On Windows, python3.exe in PATH
# is often the Microsoft Store stub that just prints an install hint, and
# the system python may be too old, so prefer the py launcher when present.
need_py="import sys; sys.exit(0 if sys.version_info >= (3, 9) else 1)"
PYTHON=
for cand in python3 python "py -3"; do
  if $cand -c "$need_py" >/dev/null 2>&1; then
    PYTHON="$cand"
    break
  fi
done
if [[ -z "$PYTHON" ]]; then
  echo "No Python >= 3.9 found (need python3, python, or py -3)" >&2
  exit 1
fi

today="$(date +%Y-%m-%d)"

stamp_for() {
  # Derive a (date, name) stamp for the given path.
  # If the working tree under that path has uncommitted changes, stamp with
  # today and a triple derived from a hash of the diff content — so a render
  # before commit already shows a fresh stamp, and the date lines up with the
  # commit day in the usual render -> commit -> push flow.
  # Otherwise, stamp from the most recent commit touching the path.
  # Falls back to today + "local draft" if neither yields a hash.
  local target_rel="$1"
  local hash date name
  if ! git -C "$REPO_ROOT" diff --quiet HEAD -- "$target_rel" 2>/dev/null; then
    date="$today"
    hash="$(git -C "$REPO_ROOT" diff HEAD -- "$target_rel" 2>/dev/null \
            | git hash-object --stdin 2>/dev/null \
            | cut -c1-7)"
  else
    hash="$(git -C "$REPO_ROOT" log -1 --format='%h' -- "$target_rel" 2>/dev/null || true)"
    date="$(git -C "$REPO_ROOT" log -1 --format='%ad' --date=short -- "$target_rel" 2>/dev/null || true)"
  fi
  if [[ -z "$hash" ]]; then
    date="$today"
    name="local draft"
  else
    name="$($PYTHON "$SCRIPT_DIR/version_word.py" "$hash" \
      "$WORDS_DIR/adjectives.txt" \
      "$WORDS_DIR/fruits.txt" \
      "$WORDS_DIR/tiere.txt")"
  fi
  printf '%s\t%s\n' "$date" "$name"
}

{
  echo "% generated by tools/update_chapter_versions.sh -- do not edit"

  # Book-level stamp: most recent commit anywhere under the book directory.
  # Used by \printbookversion on the copyright page.
  book_rel="${BOOK_DIR#$REPO_ROOT/}"
  IFS=$'\t' read -r book_date book_name < <(stamp_for "$book_rel")
  printf '\\setbookversion{%s}{%s}\n' "$book_date" "$book_name"

  for f in "$BOOK_DIR"/chapters/*.tex; do
    [[ -e "$f" ]] || continue
    base="$(basename "$f" .tex)"
    rel="${f#$REPO_ROOT/}"
    IFS=$'\t' read -r ch_date ch_name < <(stamp_for "$rel")
    printf '\\setchapterversion{%s}{%s}{%s}\n' "$base" "$ch_date" "$ch_name"
  done
} > "$OUT"

echo "Wrote $OUT"
